//! 付费专栏、读者身份、订单和文章访问级别。

use sea_orm_migration::prelude::*;

/// 新增订阅所需结构，旧文章保持公开。
#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    /// 使用 SeaQuery 建表并添加文章访问字段。
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("paid_columns"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("public_id"))
                            .uuid()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("slug"))
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Alias::new("title")).string().not_null())
                    .col(ColumnDef::new(Alias::new("description")).text().not_null())
                    .col(
                        ColumnDef::new(Alias::new("price_cents"))
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updated_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("articles"))
                    .add_column(ColumnDef::new(Alias::new("paid_column_public_id")).uuid())
                    .add_column(
                        ColumnDef::new(Alias::new("subscriber_only"))
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .add_column(ColumnDef::new(Alias::new("preview_document")).json_binary())
                    .add_column(ColumnDef::new(Alias::new("preview_html")).text())
                    .to_owned(),
            )
            .await?;
        manager
            .create_foreign_key(
                ForeignKey::create()
                    .name("fk-articles-paid-column")
                    .from(Alias::new("articles"), Alias::new("paid_column_public_id"))
                    .to(Alias::new("paid_columns"), Alias::new("public_id"))
                    .on_delete(ForeignKeyAction::Restrict)
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("reader_users"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("public_id"))
                            .uuid()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("username"))
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("password_hash"))
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("column_subscriptions"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("reader_id"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("paid_column_id"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("column_subscriptions"), Alias::new("reader_id"))
                            .to(Alias::new("reader_users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(
                                Alias::new("column_subscriptions"),
                                Alias::new("paid_column_id"),
                            )
                            .to(Alias::new("paid_columns"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx-column-subscriptions-reader-column")
                    .table(Alias::new("column_subscriptions"))
                    .col(Alias::new("reader_id"))
                    .col(Alias::new("paid_column_id"))
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("column_orders"))
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("reader_id"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("paid_column_id"))
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("amount_cents"))
                            .integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("status")).string().not_null())
                    .col(
                        ColumnDef::new(Alias::new("wechat_transaction_id"))
                            .string()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("created_at"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("paid_at")).timestamp_with_time_zone())
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("column_orders"), Alias::new("reader_id"))
                            .to(Alias::new("reader_users"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .from(Alias::new("column_orders"), Alias::new("paid_column_id"))
                            .to(Alias::new("paid_columns"), Alias::new("id"))
                            .on_delete(ForeignKeyAction::Restrict),
                    )
                    .to_owned(),
            )
            .await
    }

    /// 按依赖顺序移除新增结构。
    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        for table in ["column_orders", "column_subscriptions", "reader_users"] {
            manager
                .drop_table(Table::drop().table(Alias::new(table)).to_owned())
                .await?;
        }
        manager
            .drop_foreign_key(
                ForeignKey::drop()
                    .name("fk-articles-paid-column")
                    .table(Alias::new("articles"))
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("articles"))
                    .drop_column(Alias::new("paid_column_public_id"))
                    .drop_column(Alias::new("subscriber_only"))
                    .drop_column(Alias::new("preview_document"))
                    .drop_column(Alias::new("preview_html"))
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Alias::new("paid_columns")).to_owned())
            .await
    }
}
