/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgentRouteImport } from './routes/admin.agent'
import { Route as AdminAssetsRouteImport } from './routes/admin.assets'
import { Route as AdminColumnsRouteImport } from './routes/admin.columns'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminNotionRouteImport } from './routes/admin.notion'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as ColumnsIndexRouteImport } from './routes/columns.index'
import { Route as ColumnsSlugRouteImport } from './routes/columns.$slug'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as AdminArticlesPublicIdRouteImport } from './routes/admin.articles.$publicId'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentRoute = AdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColumnsRoute = AdminColumnsRouteImport.update({
  id: '/columns',
  path: '/columns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotionRoute = AdminNotionRouteImport.update({
  id: '/notion',
  path: '/notion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnsIndexRoute = ColumnsIndexRouteImport.update({
  id: '/columns/',
  path: '/columns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColumnsSlugRoute = ColumnsSlugRouteImport.update({
  id: '/columns/$slug',
  path: '/columns/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesPublicIdRoute = AdminArticlesPublicIdRouteImport.update({
  id: '/articles/$publicId',
  path: '/articles/$publicId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/projects': typeof ProjectsRoute
  '/reader': typeof ReaderRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/columns': typeof AdminColumnsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/notion': typeof AdminNotionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/columns/$slug': typeof ColumnsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/columns/': typeof ColumnsIndexRoute
  '/admin/articles/$publicId': typeof AdminArticlesPublicIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/projects': typeof ProjectsRoute
  '/reader': typeof ReaderRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/columns': typeof AdminColumnsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/notion': typeof AdminNotionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/columns/$slug': typeof ColumnsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/columns': typeof ColumnsIndexRoute
  '/admin/articles/$publicId': typeof AdminArticlesPublicIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/projects': typeof ProjectsRoute
  '/reader': typeof ReaderRoute
  '/admin/agent': typeof AdminAgentRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/columns': typeof AdminColumnsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/notion': typeof AdminNotionRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/columns/$slug': typeof ColumnsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/columns/': typeof ColumnsIndexRoute
  '/admin/articles/$publicId': typeof AdminArticlesPublicIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/projects'
    | '/reader'
    | '/admin/agent'
    | '/admin/assets'
    | '/admin/columns'
    | '/admin/comments'
    | '/admin/notion'
    | '/admin/settings'
    | '/articles/$slug'
    | '/categories/$slug'
    | '/columns/$slug'
    | '/tags/$slug'
    | '/admin/'
    | '/columns/'
    | '/admin/articles/$publicId'
    | '/admin/articles/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/projects'
    | '/reader'
    | '/admin/agent'
    | '/admin/assets'
    | '/admin/columns'
    | '/admin/comments'
    | '/admin/notion'
    | '/admin/settings'
    | '/articles/$slug'
    | '/categories/$slug'
    | '/columns/$slug'
    | '/tags/$slug'
    | '/admin'
    | '/columns'
    | '/admin/articles/$publicId'
    | '/admin/articles/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/projects'
    | '/reader'
    | '/admin/agent'
    | '/admin/assets'
    | '/admin/columns'
    | '/admin/comments'
    | '/admin/notion'
    | '/admin/settings'
    | '/articles/$slug'
    | '/categories/$slug'
    | '/columns/$slug'
    | '/tags/$slug'
    | '/admin/'
    | '/columns/'
    | '/admin/articles/$publicId'
    | '/admin/articles/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchiveRoute: typeof ArchiveRoute
  ProjectsRoute: typeof ProjectsRoute
  ReaderRoute: typeof ReaderRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ColumnsSlugRoute: typeof ColumnsSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
  ColumnsIndexRoute: typeof ColumnsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent': {
      id: '/admin/agent'
      path: '/agent'
      fullPath: '/admin/agent'
      preLoaderRoute: typeof AdminAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/columns': {
      id: '/admin/columns'
      path: '/columns'
      fullPath: '/admin/columns'
      preLoaderRoute: typeof AdminColumnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notion': {
      id: '/admin/notion'
      path: '/notion'
      fullPath: '/admin/notion'
      preLoaderRoute: typeof AdminNotionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columns/': {
      id: '/columns/'
      path: '/columns'
      fullPath: '/columns/'
      preLoaderRoute: typeof ColumnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/columns/$slug': {
      id: '/columns/$slug'
      path: '/columns/$slug'
      fullPath: '/columns/$slug'
      preLoaderRoute: typeof ColumnsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$publicId': {
      id: '/admin/articles/$publicId'
      path: '/articles/$publicId'
      fullPath: '/admin/articles/$publicId'
      preLoaderRoute: typeof AdminArticlesPublicIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentRoute: typeof AdminAgentRoute
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminColumnsRoute: typeof AdminColumnsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminNotionRoute: typeof AdminNotionRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesPublicIdRoute: typeof AdminArticlesPublicIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentRoute: AdminAgentRoute,
  AdminAssetsRoute: AdminAssetsRoute,
  AdminColumnsRoute: AdminColumnsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminNotionRoute: AdminNotionRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesPublicIdRoute: AdminArticlesPublicIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchiveRoute: ArchiveRoute,
  ProjectsRoute: ProjectsRoute,
  ReaderRoute: ReaderRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ColumnsSlugRoute: ColumnsSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
  ColumnsIndexRoute: ColumnsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
